### ISSUE TITLE
Ubuntu 20.04 - Tutorial 4 - Motion tracker has no attribute 'flag_saver_colour"

### ISSUE THREAD

**Issue by agporto** [mluerig/phenopype#13]
When running tutorial 4 on an Ubuntu 20.04 system, I am getting the following error:

Time: 00:00/00:15 - Frames: 1/450
Time: 00:00/00:15 - Frames: 2/450
Time: 00:00/00:15 - Frames: 3/450
Time: 00:00/00:15 - Frames: 4/450
Time: 00:00/00:15 - Frames: 5/450 - captured
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-e1d7d890b093> in <module>
----> 1 coordinates = mt.run_tracking()

~/miniconda3/envs/pp/lib/python3.7/site-packages/phenopype/tracking.py in run_tracking(self, feedback, canvas, overlay_weight)
    542                 # save output
    543                 if self.flag_save_video == True:
--> 544                     if self.flag_save_colour and len(self.canvas.shape) < 3:
    545                         self.canvas = cv2.cvtColor(self.canvas, cv2.COLOR_GRAY2BGR)
    546                     self.writer.write(self.canvas)

AttributeError: 'motion_tracker' object has no attribute 'flag_save_colour'

**Comment by agporto** [comment]
The error seems to occur when the output video path does not exist. By changing the output video file path, I resolved the issue on my end.

**Comment by mluerig** [comment]
thanks for tracking this, I'll follow it up
