### ISSUE TITLE
Ubuntu 20.04 - AttributeError: module 'phenopype.core.preprocessing' has no attribute 'create_scale'

### ISSUE THREAD

**Issue by agporto** [mluerig/phenopype#14]
In example 1, I am getting the following error: 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-c93ff899e059> in <module>
----> 1 img_data, masks = pp.preprocessing.create_scale(image, 
      2                                                 mask=True,
      3                                                 df_image_data=img_data,
      4                                                 df_masks=masks)

AttributeError: module 'phenopype.core.preprocessing' has no attribute 'create_scale'

A quick look at the source code suggests that sometime in February there were some changes on how scale was handled. This error is present in multiple examples (1, 2, 6 and 8)

**Comment by mluerig** [comment]
fixed after package re-design for 3.0.0
